### ISSUE TITLE
Makefile.PL misses $ORACLE_HOME/sdk/demo/demo.mk

### ISSUE THREAD

**Issue by ikzelf** [pythian/DBD-Oracle#20]
Hi,
could the search for the proc make file be extended to also look into $ORACLE_HOME/sdk/demo/demo.mk, as this is the path that is created for the MacOSx instant client, like:
    my @mk_oci64 = (
  'rdbms/demo/demo_xe.mk',
  'rdbms/lib/oracle.mk',
  'sdk/demo/demo.mk',
  'rdbms/demo/oracle.mk',

thanks,

**Comment by mjegh** [comment]
I've submitted a pull request for this.

**Comment by deanpearce** [comment]
This issue was addressed through other pull requests, `sdk/demo/demo.mk` is now included in both the 32 and 64bit arrays.
