### ISSUE TITLE
trouble on install

### ISSUE THREAD

**Issue by mpoche** [pythian/DBD-Oracle#30]
Following error is happening on make
gcc: error: unrecognized command line option '-bI:/usr/lib/iocp.exp'

System environment is:
OS: AIX 7.1 TL3 SP5
Perl: 5.22.0 with DBI 1.633
gcc: 4.8.3
Oracle: Client 12.1.0.2.0

DBD-Oracle installed with Oracle Client 12.1.0.1 on 2 other machines (same OS, Perl, & gcc levels).

I have a script file with the full output of perl Makefile.PL and make.

**Comment by mjegh** [comment]
I believe the compile pulls the options from the Oracle makefiles. If you use a different compiler it won't work. You may get away with editing the Makefile after it is generated. Also read the AIX readme at http://search.cpan.org/~pythian/DBD-Oracle-1.74/lib/DBD/Oracle/Troubleshooting/Aix.pod

**Comment by mpoche** [comment]
I'm using the same compiler to install DBD-Oracle that I used to install Perl 5.22.  For the Oracle client, I used Oracle's built-in installer.  I'm not sure what edits I need to make to the Makefile to complete the installation.  I tried remove the -bI line that gcc doesn't like.  The module installed, but then nothing would connect.

One thing that changed from Oracle 12.1.0.1 to 12.1.0.2 is that update 2 required I/O Completion Ports (iocp) be made available in AIX.  AIX defaults iocp to Defined instead.  Without iocp being available the Oracle client would not install.

**Comment by mjegh** [comment]
What I meant is I think you'll have more success if you use the same compiler oracle used throughout.

I don't have access to an AIX machine right now. I think you'd get a wider audience for help with this on the dbi-users mailing list (see http://dbi/perl/org) or perhaps perlmonks or stackoverflow.

**Comment by mpoche** [comment]
I got an answer from Stackoverflow.  I had to put -Wl, in front of the -bI.  There were other lines in the Makefile that had it, but the 2 lines for iocp did not.  Once I added that the installation finished normally.

Thank you for your help
