### ISSUE TITLE
Error in $sth->{PRECISION} call

### ISSUE THREAD

**Issue by cliveholloway** [pythian/DBD-Oracle#33]
Noticed this when migrating code to a new server. Using Oracle 11.2.0.4

Affects CHAR fields too - and possibly more. Feels like a bit shift bug maybe.

Code works as expected on CentOS under DBD::Oracle v1.64 (prints 10), fails under v1.74 (prints 40).
# !/usr/bin/perl

use strict;
use warnings;
use DBI;

my $dbh = DBI->connect(...connect args to oracle db...);
$dbh->do("CREATE TABLE test__table(testfield VARCHAR2(10))") 
    or die "Can't create table: $DBI::errstr";
my $sth= $dbh->prepare("SELECT \* FROM test__table");
print $sth->{PRECISION}->[0].$/;
$dbh->do("DROP TABLE test__table");

**Comment by cliveholloway** [comment]
Looks like a similar issue to:

https://rt.cpan.org/Public/Bug/Display.html?id=78700

**Comment by cliveholloway** [comment]
Can close this. Erroious setting of NLS_LANG environment vsar caused the issue (setting it to UTF8, when it shouldn't have been).

**Comment by djzort** [comment]
Why not close it?

**Comment by cliveholloway** [comment]
No idea - have no memory of this. Let's try again.
