### ISSUE TITLE
During make test: 31lob.t fails: "2/12 DBI::db=HASH(0x1ae2fc8)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at t/31lob.t line 216."

### ISSUE THREAD

**Issue by otheus** [pythian/DBD-Oracle#48]
This is with Oracle 12.2 client on Linux, 64-bit. Can anyone else duplicate this problem?

The problem arose from one day to the next. Later on, there is a failure because the quota for that schema/user is full. IDeas?

**Comment by deanpearce** [comment]
Almost seems like two separate issues - the test error is simply missing an `undef $sth;` before disconnecting. That said, not disconnecting a statement handle shouldn't be causing quota problems.

**Comment by deanpearce** [comment]
Fixed the actual error in the test, closing issue.
