### ISSUE TITLE
Support for open source OCILIB

### ISSUE THREAD

**Issue by djzort** [pythian/DBD-Oracle#55]
OCILIB is an open source Oracle driver that seems to have active development.

Perhaps it can be supported (although a dedicated fork might be prudent)

See 
https://github.com/vrogier/ocilib
http://ocilib.net

**Comment by djzort** [comment]
oh its just a wrapper

**Comment by cjbj** [comment]
The real question is whether DBD::Oracle should be rewritten on top of a wrapper like OCILIB or [ODPI-C](https://oracle.github.io/odpi/) - which is designed for language drivers and being used by Python, Node.js etc.
